name: Build and Release to mod portal

# Controls when the workflow will run
on:
  release:
    types: [released]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'mod'
      
      - name: Download rfmp
        uses: robinraju/release-downloader@v1
        with:
          repository: JohnTheCoolingFan/rfmp
          fileName: rfmp-linux
          latest: true
      
      - name: Get full mod file name
        run: |
          MFNAME=$(jq -r '.name + "_" + .version + ".zip"' ./mod/info.json)
          echo "MODFILENAME=$MFNAME" >> $GITHUB_ENV

      - name: Pack a mod
        run: |
          chmod +x ./rfmp-linux
          (cd mod; ../rfmp-linux --no-clean --install-dir ../)
      
      - name: Upload file to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.MODFILENAME }}

      - name: Publish mod on mod portal
        uses: JohnTheCoolingFan/factorio-mod-publish@v1
        with:
          factorio_token: ${{ secrets.FACTORIO_TOKEN }}
          info_json_file: './mod/info.json'

      - name: Send notification on Discord
        uses: JohnTheCoolingFan/factorio-mod-discord-announce@v1
        with:
          discord_webhook: ${{ secrets.DISCORD_NEW_WEBHOOK }}
          info_json_file: './mod/info.json'
          changelog_file: './mod/changelog.txt'

      - name: Process README for mod portal
        run: |
          sed 's/!\[\(.\+\)\](\(.\+\))/![\1](https:\/\/raw\.githubusercontent\.com\/JohnTheCoolingFan\/EquipmentGridLess\/refs\/heads\/main\/\2)/' mod/README.md > README-mod-portal.md

      - name: Update mod portal description
        uses: JohnTheCoolingFan/factorio-mod-details@v1
        with:
          factorio_token: ${{ secrets.FACTORIO_TOKEN }}
          mod_name: EquipmentGridLess
          description_file: README-mod-portal.md

